server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/microservices
      database: microservices
      auto-index-creation: true

  application:
    name: Rating-Service

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true  
    register-with-eureka : true
    service-url:
     defaultZone: http://localhost:8761/eureka      